version: '3.7'
services: 
    postgres:
        image: postgres:15
        container_name: postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: sgv
        ports:
          - "5432:5432"
        networks:
          - servicios
        restart: always
    servicio-eureka-server:
        build: ./servicio-eureka-server-master
        image: springboot-servicio-eureka-server:v1
        ports: 
            - "8761:8761"
        restart: always
        networks: 
                - servicios
    servicio-usuarios:
        build: ./servicio-usuarios-master
        image: servicio-usuarios:v1
        restart: always
        networks: 
                - servicios
        depends_on: 
            - servicio-eureka-server
            - postgres
    servicio-zuul-server:
        build: ./servicio-zuul-server-master
        image: springboot-servicio-zuul-server:v1
        ports: 
            - "8090:8090"
        restart: always
        networks: 
                - servicios
        depends_on: 
            - servicio-eureka-server
    servicio-oauth:
        build: ./servicio-oauth-master
        image: springboot-servicio-oauth:v1
        ports: 
            - "9100:9100"
        restart: always
        networks: 
                - servicios
        depends_on: 
            - servicio-eureka-server 
networks: 
    servicios: {}