spring.application.name=zuul-server

#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.client.service-url.defaultZone=http://servicio-eureka-server:8761/eureka

zuul.routes.security.service-id=servicio-oauth
zuul.routes.security.path=/api/security/**

zuul.routes.usuarios.service-id=servicio-usuarios
zuul.routes.usuarios.path=/api/usuarios/**

zuul.routes.usuarios.service-id=api-gestor
zuul.routes.usuarios.path=/api/gestor/**


zuul.sensitiveHeaders=Cookie,Set-Cookie

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 150000000
ribbon.ConnectTimeout: 300000
ribbon.ReadTimeout: 1000000

eureka.instance.preferIpAddress=true
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.client.healthcheck.enabled=true

zuul.host.connect-timeout-millis=600000000
zuul.host.max-per-route-connections=100000000
zuul.host.max-total-connections=50000000
zuul.host.socket-timeout-millis=600000000
zuul.semaphore.max-semaphores=5000000
zuul.ribbon.eager-load.enabled= true

#spring.sleuth.sampler.probability=1.0
#spring.zipkin.baseUrl=http://servicio-commons-zipkin:9411

logging.file.name= ./log/zuul.log

## MULTIPART (Propiedades de varias partes)
# Habilitar cargas multiparte
spring.servlet.multipart.enabled = true
server.tomcat.max-swallow-size=7700KB
# Umbral después del cual los archivos se escriben en el disco.
# spring.servlet.multipart.file-size-threshold = 7680KB
# Tamaño máximo de archivo.
# spring.servlet.multipart.max-file-size = 7680KB
spring.servlet.multipart.max-file-size = 7700KB
maxFileSize = 7864320 
# Tamaño máximo de solicitud
# spring.servlet.multipart.max-request-size = 7700KB
spring.servlet.multipart.max-request-size = 7700KB
