spring.application.name=servicio-zuul-server

eureka.client.serviceUrl.defaultZone=http://servicio-eureka-server:8761/eureka

zuul.routes.principal.service-id=oga-servicio-principal
zuul.routes.principal.path=/api/principal/**

zuul.routes.usuarios.service-id=oga-servicio-usuarios
zuul.routes.usuarios.path=/api/usuarios/**

zuul.routes.sae.service-id=oga-servicio-sae
zuul.routes.sae.path=/api/sae/**

zuul.routes.expedientes.service-id=oga-servicio-expedientes
zuul.routes.expedientes.path=/api/expedientes/**
zuul.routes.videos.service-id=oga-servicio-videos
zuul.routes.videos.path=/api/videos/**


zuul.routes.abogados.service-id=oga-servicio-abogados
zuul.routes.abogados.path=/api/abogados/**

zuul.routes.security.service-id=servicio-oauth
zuul.routes.security.path=/api/security/**
zuul.routes.security.sensitive-headers=Cookie,Set-Cookie

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 1500000
ribbon.ConnectTimeout: 3000
ribbon.ReadTimeout: 10000

server.ssl.key-store = keystore.p12
server.ssl.key-store-password = fLE7Smr8
server.ssl.key-store-type = PKCS12

