eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug
logging.file.name= ./log/oauth.log

#spring.sleuth.sampler.probability=1.0
#spring.zipkin.baseUrl=http://servicio-commons-zipkin:9411
