eureka.client.service-url.defaultZone=http://servicio-eureka-server:8761/eureka/

spring.datasource.url=jdbc:postgresql://ogasprdesa.pjtuc.gov.ar:5432/oga?ssl=true&sslmode=require
spring.datasource.username=oga
spring.datasource.password=Og4$pr1ng